### ISSUE TITLE
Darren has this issue with google sign-in

### ISSUE THREAD

**Issue by eddieberklee** [eddieberklee/android-meet-in-the-middle#31]
https://www.google.com/search?sourceid=chrome-psyapi2&ion=1&espv=2&ie=UTF-8&q=invalid%20audience%20google%20api&oq=invalid%20audience%20google%20api&aqs=chrome..69i57j69i60l2.4480j0j7

**Comment by ambardhesi** [comment]
This still an issue?

**Comment by eddieberklee** [comment]
I don't think he ever tested it - but one thing I came across is this same
behavior happening without any warning message when there's no internet
connection. Hence the new screen I mocked up and added to Trello.

**Comment by DarrenPoh** [comment]
soz didnt test this. since i signed in using email

**Comment by eddieberklee** [comment]
Hi eddieberklee/android,

I'd like to add you to my professional network on LinkedIn.
- Edward

Confirm that you know Edward: https://www.linkedin.com/e/v2?e=0-ir4ijdez-df&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=hmaYHTcU&invitationId=6163953554483658754

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ir4ijdez-df&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHKWGn2tlmfGAAAAVYrDOl7EufF1SO8q_YPmc6IfUvUMAgjSeP2k5X3plZRyizMtYbHwCq6TTXXct-8Cv8biTeMjfrstCcFWmOoPmrewDX2r5I6gGp4i1UUJ14lVEsmznQi1JrjTckZV_wji7D-7UeXEbN9xgg5Uw0yPVWExGanmeM_BgatDPXCawN2I0S1Sqiz&eid=0-ir4ijdez-df

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ir4ijdez-df&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by eddieberklee** [comment]
Edward Lee would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=rd9azw-irdxn3qg-os&t=ssuw&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=hmaYHTcU&invitationId=6163953554483658754

View Edward Lee&#39;s profile: https://www.linkedin.com/e/v2?e=rd9azw-irdxn3qg-os&t=ssuw&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=hmaYHTcU&invitationId=6163953554483658754

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=rd9azw-irdxn3qg-os&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=rd9azw-irdxn3qg-os&loid=AQHhPanZLso15wAAAVZOISokOepHiuxbeff6EMjSPVG54AOTCtg-PD-3Vf9iGko0bQ_fkrrJKqMftSCa5X2Er5KlCgGWmmyiwbrXQ8MjVWB8Jq8_f4JwsUfBE2NC7XxjVuUhVDIPhhzeS-2DLJ2XFvYMgI8PTrnZlHs6UbfXXSwpWRyhtEhaXnkyedlcxeJFSTaS

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=rd9azw-irdxn3qg-os&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by eddieberklee** [comment]
Hi eddieberklee/android,

Edward Lee would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=rd9azw-irnoy5ux-i9&t=ssuw&ek=second_guest_reminder_01&li=70&m=hero&ts=accept_text&sharedKey=hmaYHTcU&invitationId=6163953554483658754

View Edward Lee&#39;s profile: https://www.linkedin.com/e/v2?e=rd9azw-irnoy5ux-i9&t=ssuw&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=hmaYHTcU&invitationId=6163953554483658754

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=rd9azw-irnoy5ux-i9&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=72&m=unsub&ts=HTML&eid=rd9azw-irnoy5ux-i9&loid=AQEyoIZlFK9JZQAAAVZxVltYYcJ7kfyX1VxzPuRMjLvVSTLiG27d1rUJ8BHCXx6bUMMW3FMS_XdbxG4dJA3rohsjWik3Xfk3aEw5BIkEQ328BiW_eBim6N4-SSEWYvfEqqksJj6WhesAQIESIy59qsjxVJ2FUNg_uivaomMvYqWyduS3blytRlh3uIqfPn1IR-1w

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=rd9azw-irnoy5ux-i9&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
